[build]
  command = "mkdir -p ../themes && ln -sfn \"$PWD\" ../themes/WebStack-Hugo && cd exampleSite && hugo --themesDir ../../themes --baseURL \"${DEPLOY_PRIME_URL:-$URL}\""
  publish = "exampleSite/public"

[build.environment]
  HUGO_VERSION = "0.122.0"
  HUGO_ENV = "production"
